type: app
description: Default stackfile usecase description
# template used to create the project
template: jupyter-pyspark-stack/jupyter-pyspark
# list of plugins to be applied after project creation